apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: oura-pg
    type: grafana-postgresql-datasource
    access: proxy
    url: $POSTGRES_HOST:$POSTGRES_PORT
    database: $POSTGRES_DB
    user: $GRAFANA_DB_USER
    isDefault: true
    jsonData:
      sslmode: disable
      postgresVersion: 1800
    secureJsonData:
      password: $GRAFANA_DB_PASSWORD
